name: debug_env
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - langchain
    - langchain
    - langchain-openai
    - langchain-community
    - langgraph
    - yfinance
    - openbb[all]
    - numpy==1.26.3
